import pygame
pygame.init()

class Help:
    mapsize1 = pygame.image.load("graphics\\info\\mapsize1.png")
    mapsize1.set_colorkey((255,255,255))
    mapsize2 = pygame.image.load("graphics\\info\\mapsize2.png")
    mapsize2.set_colorkey((255,255,255))
    mapname = pygame.image.load("graphics\\info\\mapname.png")
    mapname.set_colorkey((255,0,0))
    changename = pygame.image.load("graphics\\info\\changename.png")
    changename.set_colorkey((255,0,0))
    size = pygame.image.load("graphics\\info\\mapsize.png")
    size.set_colorkey((255,0,0))
    create = pygame.image.load("graphics\\info\\create.png")
    create.set_colorkey((255,0,0))

    changemap = pygame.image.load("graphics\\info\\changemap.png")
    changemap.set_colorkey((255,0,0))
    loadmap = pygame.image.load("graphics\\info\\loadmap.png")
    loadmap.set_colorkey((255,0,0))
    loadmapname = pygame.image.load("graphics\\info\\loadmapname.png")
    loadmapname.set_colorkey((255,0,0))

persona = pygame.image.load("graphics\\persona.png")
resourcebar = pygame.image.load("graphics\\resourcebar.png")
resourcebar.set_colorkey((255,255,255)) # Make all (255,255,255) transparent
food = pygame.image.load("graphics\\food.png")
food.set_colorkey((255,255,255))
stoner = pygame.image.load("graphics\\stone.png")
stoner.set_colorkey((255,255,255))
steelr = pygame.image.load("graphics\\steel.png")
steelr.set_colorkey((255,255,255))
woodr = pygame.image.load("graphics\\wood.png")
woodr.set_colorkey((255,255,255))
grid = pygame.image.load("graphics\\grid.png")
test = pygame.image.load("graphics\\test.png")
seldef = sel = pygame.image.load("graphics\\sel.png")
sidebar = pygame.image.load("graphics\\side.jpg")
arrowupimg = pygame.image.load("graphics\\arrowup.png")
arrowdownimg = pygame.image.load("graphics\\arrowdown.png")
buildimg = pygame.image.load("graphics\\building.png")
buildimg2 = pygame.image.load("graphics\\building.png")
buildimg3 = pygame.image.load("graphics\\building.png")
buildimg4 = pygame.image.load("graphics\\building.png")
buildimg5 = pygame.image.load("graphics\\building.png")
xbuttoni = pygame.image.load("graphics\\xbutton.png")
scrimg = pygame.image.load("graphics\\screenshot.png")
savebutton = pygame.image.load("graphics\\savebutton.png")
nobuild = pygame.image.load("graphics\\nobuild.png")
bulldoze = pygame.image.load("graphics\\bulldoze.png")
b_house = pygame.image.load("graphics\\house.png")
b_bakery = pygame.image.load("graphics\\bakery.png")
i_house = pygame.image.load("graphics\\icons\\house.png")
i_bakery = pygame.image.load("graphics\\icons\\bakery.png")

sandboxi = pygame.image.load("graphics\\sandbox.png")
updateresources = pygame.image.load("graphics\\updateresources.png")
resetresources = pygame.image.load("graphics\\resetresources.png")

b_downleft = pygame.image.load("graphics\\roads\\downleft.png")
b_downleft.set_colorkey((255,255,255))
b_downright = pygame.image.load("graphics\\roads\\downright.png")
#b_downright.set_colorkey((255,255,255))
b_horizontal = pygame.image.load("graphics\\roads\\horizontal.png")
b_horizontal.set_colorkey((255,255,255))
b_leftdown = pygame.image.load("graphics\\roads\\leftdown.png")
#b_leftdown.set_colorkey((255,255,255))
#b_leftup = pygame.image.load("graphics\\roads\\leftup.png")
b_rightdown = pygame.image.load("graphics\\roads\\rightdown.png")
b_rightdown.set_colorkey((255,255,255))
#b_rightup = pygame.image.load("graphics\\roads\\rightup.png")
#b_upleft = pygame.image.load("graphics\\roads\\upleft.png")
#b_upright = pygame.image.load("graphics\\roads\\upright.png")
b_vertical = pygame.image.load("graphics\\roads\\vertical.png")
b_vertical.set_colorkey((255,255,255))

i_downleft = pygame.image.load("graphics\\roads\\idownleft.png")
i_downright = pygame.image.load("graphics\\roads\\idownright.png")
i_horizontal = pygame.image.load("graphics\\roads\\ihorizontal.png")
i_leftdown = pygame.image.load("graphics\\roads\\ileftdown.png")
#i_leftup = pygame.image.load("graphics\\roads\\ileftup.png")
i_rightdown = pygame.image.load("graphics\\roads\\irightdown.png")
#i_rightup = pygame.image.load("graphics\\roads\\irightup.png")
#i_upleft = pygame.image.load("graphics\\roads\\iupleft.png")
#i_upright = pygame.image.load("graphics\\roads\\iupright.png")
i_vertical = pygame.image.load("graphics\\roads\\ivertical.png")

appletree_0 = pygame.image.load("graphics\\appletree_0.png")
appletree_1 = pygame.image.load("graphics\\appletree_1.png")
